### PR TITLE
Add HWPE-MAC for Bender

### PR DESCRIPTION
**Pull request by xiaoling-yi**
I am doing a mini experiment on git pull request. Please make comments.

### CODE REVIEW

**Comment by rgantonio** [comment]
Hey @xiaoling-yi !

Just an FYI, but when you make or describe PRs, it's best to describe in the description the literal intent of making the PR.

If you check my other PRs, I tried to give overviews of what I wanted to do. I learned the hard way that making it more descriptive makes other users or readers understand what we are going to do.

In this case you could say "This PR adds the HWPE mac engine to the source list for Verilator builds" or such 🔥 

I will look into the problem and make suggestions to fix the failed build 😄

**Comment by rgantonio** [comment]
Actually @xiaoling-yi  you could edit the description in here 😄  so I will let you decide on what to put!

**Comment by rgantonio** [comment]
@xiaoling-yi here is the fix! Please check this commit [256ceb5](https://github.com/KULeuven-MICAS/snitch_cluster/pull/1/commits/256ceb58961b552d1111644713c478b246b87ed7)

I suggest you experiment do this by just invoking:

```bash
git cherry-pick [256ceb5](https://github.com/KULeuven-MICAS/snitch_cluster/pull/1/commits/256ceb58961b552d1111644713c478b246b87ed7)
```

**Comment by xiaoling-yi** [comment]
@rgantonio Ok! I think this issue is solved using your method!

**Comment by xiaoling-yi** [comment]
This PR adds the HWPE mac engine to the source list for Verilator builds.

**Comment by rgantonio** [comment]
> @rgantonio Ok! I think this issue is solved using your method!

Let's wait for the build to finish :) then call me to squash and merge. So we don't do the same mistake I did yesterday.

Good job!!!

**Review by rgantonio — APPROVED** [review]
Nice! 😄 

In the next PR, let's add the HWPE MAC engine!

**Comment by xiaoling-yi** [comment]
Done!

**Comment by JosseVanDelm** [comment]
Wicked @rgantonio @xiaoling-yi

**Pull request merged**
