### PR TITLE
make compatible with verilator 5

### PR DESCRIPTION
**Pull request by jorendumoulin**
changes:

- add `--timing` flag (which is now required)
- add required cobj arguments
- update c++ version

### CODE REVIEW

**Comment by jorendumoulin** [comment]
@rgantonio @xiaoling-yi  The failing CI test (ci / Simulate SW on SNAX Streamer GEMM Cluster w/ Verilator (Generic LLVM), seems to be failing for a reason unrelated to my changes, and also failed on the main branch. Could you help me out with this?

**Comment by xiaoling-yi** [comment]
Hi @jorendumoulin , I can have a look at it! It is a bit strange that in the pull request, there is no error  https://github.com/KULeuven-MICAS/snitch_cluster/pull/92, but after merging the error appears...

**Comment by xiaoling-yi** [comment]
I located the error. It is because of a wrong file in `snax-dev` bender file. We need to clean up `snax-dev` first to solve this issue...But I think we need further discussion on how to clean up `snax-dev`!...

**Comment by jorendumoulin** [comment]
can we already merge this then?

**Review by rgantonio — APPROVED** [review]
Really just these two? haha OKAY!

**Comment by rgantonio** [comment]
For documentation purposes, I think we will have to break things first so things like this are fine then we'll fix it along the way.

**Comment by JosseVanDelm** [comment]
Thanks for working on this :heart: :rocket:

**Pull request merged**
